# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xHTXuEHhUwR7aO_Sv8OK0RTnsSProvyt
"""

import pandas as pd

df = pd.DataFrame({
    'Population': [35.467, 63.951, 80.94 , 60.665, 127.061, 64.511, 318.523],
    'GDP': [
        1785387,
        2833687,
        3874437,
        2167744,
        4602367,
        2950039,
        17348075
    ],
    'Surface Area': [
        9984670,
        640679,
        357114,
        301336,
        377930,
        242495,
        9525067
    ],
    'HDI': [
        0.913,
        0.888,
        0.916,
        0.873,
        0.891,
        0.907,
        0.915
    ],
    'Continent': [
        'America',
        'Europe',
        'Europe',
        'Europe',
        'Asia',
        'Europe',
        'America'
    ]
}, columns=['Population', 'GDP', 'Surface Area', 'HDI', 'Continent'])

df.index = [
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States',
]

df.columns

df['GDP per Capita '] = round ( df['GDP'] / df['Population'] ,2)

df



df2 = pd.read_csv('/content/btc-market-price.csv' , header=None , names=['TimeStamp' , 'Price'] , index_col= 0 , parse_dates=True)

df2

ax = df2.plot(figsize=(8,4) , title='Price')

from matplotlib import pyplot as plt
df2['Price'].plot(kind='line', figsize=(8, 4), title='Price')
plt.gca().spines[['top', 'right']].set_visible(False)



df2.columns = ['Timestamp' , 'Price']
df2

df2.shape

df2.info()

df2.dtypes

df2['Timestamp']= pd.to_datetime(df2['Timestamp'])
df2.dtypes

df2

df2.set_index('Timestamp', inplace = True)

df2

df3= pd.read_csv('/content/eth-price.csv' , index_col = 0 , parse_dates = True)

df3.head()

prices = pd.DataFrame(index=df2.index)
prices

prices['Bitcoin']= df2['Price']
prices['Eather'] = df3['Value']

prices.head()

prices.plot(figsize=(8,4))

prices.loc['2017-12-01':'2018-01-01'].plot()

number_of_missing_values = prices.isnull().sum()
number_of_missing_values